server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    rewrite ^/en/report-abuse/?$ /en/report-abuse.html last;
    rewrite ^/ru/report-abuse/?$ /ru/report-abuse.html last;

    location = /en {
        return 302 /en/;
    }
    location = /ru {
        return 302 /ru/;
    }

    location /en/ {
        try_files $uri $uri/ =404;
    }
    location /ru/ {
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
